### PR TITLE
scripts/qemu-launcher.py: fixed linter warnings

### PR DESCRIPTION
**Pull request by vazhnov**
* qemu-launcher.py:11:0: W0611: Unused import time (unused-import)
* qemu-launcher.py:75:0: C0330: Wrong continued indentation (add 3 spaces).
* qemu-launcher.py:76:0: C0330: Wrong continued indentation.
* qemu-launcher.py:107:0: C0330: Wrong continued indentation (add 17 spaces).
* qemu-launcher.py:108:0: C0330: Wrong continued indentation (add 17 spaces).
* qemu-launcher.py:109:0: C0330: Wrong continued indentation.

I didn't fix:
* qemu-launcher.py:1:0: C0103: Module name "qemu-launcher" doesn't conform to snake_case naming style (invalid-name)
* qemu-launcher.py:39:23: W0613: Unused argument 'sig' (unused-argument)
* qemu-launcher.py:39:28: W0613: Unused argument 'frame' (unused-argument)

### CODE REVIEW

**Comment by rtfb** [comment]
Neat, thanks! Can we mute the remaining ones with `#pylint: disable=unused-argument` or some such?

**Comment by vazhnov** [comment]
Added:

```python
# pylint: disable=invalid-name,missing-function-docstring,unused-argument
```

**Comment by rtfb** [comment]
Great, thanks a lot, Alexey!

**Comment by rtfb** [comment]
BTW, @vazhnov, which version of pylint were you using? I'm getting this with my pylint on the current master:

```
$ pylint3 --version
No config file found, using default configuration
pylint3 1.8.3, 
astroid 1.6.0
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

$ pylint3 scripts/qemu-launcher.py 
No config file found, using default configuration
************* Module qemu-launcher
E:  3, 0: Bad option value 'missing-function-docstring' (bad-option-value)
C: 77, 0: Wrong continued indentation (remove 1 space).
           ]
          |^ (bad-continuation)
C:110, 0: Wrong continued indentation (remove 1 space).
                             )
                            |^ (bad-continuation)
C:  1, 0: Missing module docstring (missing-docstring)
C: 15, 0: Missing function docstring (missing-docstring)
C: 40, 0: Missing function docstring (missing-docstring)
C: 41, 4: Missing function docstring (missing-docstring)
C: 47, 0: Missing function docstring (missing-docstring)
C: 53, 0: Missing function docstring (missing-docstring)
C:124, 0: Missing function docstring (missing-docstring)
```

I'm presuming my pylint is old-ish since I'm on Ubuntu 18.04, but I wonder which was yours.

**Comment by vazhnov** [comment]
@rtfb , I use pylint 2.10.2 (from Gentoo):
```
$ pylint --version
pylint 2.10.2
astroid 2.7.3
Python 3.9.6 (default, Sep 16 2021, 20:34:29)
[GCC 10.3.0]
```

**Pull request merged**
